# Railway configuration for Laravel
[build]
# Build command will run during the build phase
buildCommand = "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"

[deploy]
# Health check settings
healthcheckPath = "/health"
healthcheckTimeout = 10

# Start command is now in the Procfile
startCommand = ""

[env]
# Basic Laravel configuration
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "${APP_KEY}"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"

# Database configuration (Railway will provide these)
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

# Session and cache
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"

# Logging
LOG_CHANNEL = "stderr"
LOG_LEVEL = "debug"

# Queue (set to sync by default, can be changed to database/redis)
QUEUE_CONNECTION = "sync" 