[build]
# Use Railway's PHP buildpack
builder = "heroku/buildpacks:20"

[deploy]
# Run migrations before starting the application
preDeployCommand = "php artisan migrate --force"

# Health check settings
healthcheckPath = "/"
healthcheckTimeout = 30

[env]
# Basic Laravel configuration
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "${APP_KEY}"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"

# Database configuration (Railway will provide these)
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

# Session and cache
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"

# Logging
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"

# Queue (set to sync by default, can be changed to database/redis)
QUEUE_CONNECTION = "sync"

# Required PHP extensions
PHP_EXTENSIONS = "bcmath ctype fileinfo json mbstring openssl pdo pdo_mysql tokenizer xml gd"

# PHP settings
PHP_INI_SCAN_DIR = "./php.ini"
PHP_MEMORY_LIMIT = "256M"
PHP_POST_MAX_SIZE = "100M"
PHP_UPLOAD_MAX_FILESIZE = "100M" 