[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "php artisan migrate --force"
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "redis"
QUEUE_CONNECTION = "redis"
SESSION_DRIVER = "redis"
LOG_CHANNEL = "stderr"

[[services]]
name = "web"
envs = ["PORT"]

[[services]]
name = "queue"
command = "php artisan queue:work redis --tries=3 --max-time=3600"
envs = ["PORT"] 