[build]
builder = "nixpacks"
buildCommand = "echo 'Building with Nixpacks...'"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "${APP_KEY}"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"

# Database configuration
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"

# Session and cache
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"

# Logging
LOG_CHANNEL = "stderr"
LOG_LEVEL = "debug" 