# Use Railway's built-in PHP environment instead of Nixpacks
[build]
# Use the Dockerfile in the root of the repository
builder = "dockerfile"

# Deploy configuration
[deploy]
# The command to run after the build is complete
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 15

# Environment variables
[environments]
[environments.production]
  [environments.production.variables]
    # Application settings
    APP_ENV = "production"
    APP_DEBUG = "false"
    APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
    
    # Logging
    LOG_CHANNEL = "stderr"
    LOG_LEVEL = "debug"
    
    # Database configuration (Railway will provide these)
    DB_CONNECTION = "mysql"
    DB_HOST = "${MYSQLHOST}"
    DB_PORT = "${MYSQLPORT}"
    DB_DATABASE = "${MYSQLDATABASE}"
    DB_USERNAME = "${MYSQLUSER}"
    DB_PASSWORD = "${MYSQLPASSWORD}"
    
    # Session and cache
    CACHE_DRIVER = "file"
    SESSION_DRIVER = "file"
    SESSION_LIFETIME = "120" 