# Force Nixpacks builder and disable Docker
[build]
builder = "nixpacks"

# Explicitly set the build command
[build.uses]
provider = "nixpacks"

# Deploy configuration
[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10

# Environment variables
[environments]
[environments.production]
  [environments.production.variables]
    # Application settings
    APP_ENV = "production"
    APP_DEBUG = "false"
    APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
    
    # Logging
    LOG_CHANNEL = "stderr"
    LOG_LEVEL = "debug"
    
    # Database configuration (Railway will provide these)
    DB_CONNECTION = "mysql"
    DB_HOST = "${MYSQLHOST}"
    DB_PORT = "${MYSQLPORT}"
    DB_DATABASE = "${MYSQLDATABASE}"
    DB_USERNAME = "${MYSQLUSER}"
    DB_PASSWORD = "${MYSQLPASSWORD}"
    
    # Session and cache
    CACHE_DRIVER = "file"
    SESSION_DRIVER = "file"
    SESSION_LIFETIME = "120"
    
    # Force Nixpacks
    NIXPACKS_USE_RAILWAY_WEBSERVER = "true" 