[build]
builder = "nixpacks"

[deploy]
startCommand = ""
healthcheckPath = "/health"
healthcheckTimeout = 10

[environments]
[environments.production]
  [environments.production.variables]
    APP_ENV = "production"
    APP_DEBUG = "false"
    LOG_CHANNEL = "stderr"
    LOG_LEVEL = "debug" 