[build]
  builder = "nixpacks"
  buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
  startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
  healthcheckPath = "/health"
  healthcheckTimeout = 10

[environments]
[environments.production]
  [environments.production.variables]
    APP_ENV = "production"
    APP_DEBUG = "false"
    LOG_CHANNEL = "stderr"
    LOG_LEVEL = "debug"
    
    # Database configuration
    DB_CONNECTION = "mysql"
    DB_HOST = "${MYSQLHOST}"
    DB_PORT = "${MYSQLPORT}"
    DB_DATABASE = "${MYSQLDATABASE}"
    DB_USERNAME = "${MYSQLUSER}"
    DB_PASSWORD = "${MYSQLPASSWORD}"
    
    # Session and cache
    CACHE_DRIVER = "file"
    SESSION_DRIVER = "file"
    SESSION_LIFETIME = "120" 